# coding: utf-8

"""
    products

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, conlist, validator
from products_api.models.new_product_to_measure_partial import NewProductToMeasurePartial
from typing import Union, Any, List, TYPE_CHECKING
from pydantic import StrictStr, Field

NEWPRODUCTTOMEASUREPARTIALUNION_ONE_OF_SCHEMAS = ["List[NewProductToMeasurePartial]", "NewProductToMeasurePartial"]

class NewProductToMeasurePartialUnion(BaseModel):
    """
    NewProductToMeasurePartialUnion
    """
    # data type: NewProductToMeasurePartial
    oneof_schema_1_validator: Optional[NewProductToMeasurePartial] = None
    # data type: List[NewProductToMeasurePartial]
    oneof_schema_2_validator: Optional[conlist(NewProductToMeasurePartial)] = None
    if TYPE_CHECKING:
        actual_instance: Union[List[NewProductToMeasurePartial], NewProductToMeasurePartial]
    else:
        actual_instance: Any
    one_of_schemas: List[str] = Field(NEWPRODUCTTOMEASUREPARTIALUNION_ONE_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = NewProductToMeasurePartialUnion.construct()
        error_messages = []
        match = 0
        # validate data type: NewProductToMeasurePartial
        if not isinstance(v, NewProductToMeasurePartial):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NewProductToMeasurePartial`")
        else:
            match += 1
        # validate data type: List[NewProductToMeasurePartial]
        try:
            instance.oneof_schema_2_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in NewProductToMeasurePartialUnion with oneOf schemas: List[NewProductToMeasurePartial], NewProductToMeasurePartial. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in NewProductToMeasurePartialUnion with oneOf schemas: List[NewProductToMeasurePartial], NewProductToMeasurePartial. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> NewProductToMeasurePartialUnion:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> NewProductToMeasurePartialUnion:
        """Returns the object represented by the json string"""
        instance = NewProductToMeasurePartialUnion.construct()
        error_messages = []
        match = 0

        # deserialize data into NewProductToMeasurePartial
        try:
            instance.actual_instance = NewProductToMeasurePartial.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into List[NewProductToMeasurePartial]
        try:
            # validation
            instance.oneof_schema_2_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_2_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into NewProductToMeasurePartialUnion with oneOf schemas: List[NewProductToMeasurePartial], NewProductToMeasurePartial. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into NewProductToMeasurePartialUnion with oneOf schemas: List[NewProductToMeasurePartial], NewProductToMeasurePartial. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())


