CREATE TABLE marketplaces (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

INSERT INTO
    marketplaces (name)
VALUES ('Walmart'),
    ('Target'),
    ('Kroger');

CREATE TABLE physical_marketplaces (
    open_location_code CHAR(15) PRIMARY KEY,
    marketplace_id INT NOT NULL,
    FOREIGN KEY (marketplace_id) REFERENCES marketplaces (id),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE units (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    symbol TEXT NOT NULL UNIQUE
);

INSERT INTO
    units (name, symbol)
VALUES
    -- any larger denominations should be converted to the lowest denomination
    ('fluid ounce', 'fl oz'),
    ('ounce', 'oz'),
    ('milliliter', 'mL'),
    ('gram', 'g');

CREATE TABLE products (
    gtin CHAR(14) NOT NULL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sku VARCHAR(255) NOT NULL,
    productName TEXT NOT NULL CHECK (LENGTH(productName) <= 255),
    sellsInRaw BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE products_to_measures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gtin CHAR(14) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (gtin) REFERENCES products (gtin),
    unit_id INT NOT NULL,
    FOREIGN KEY (unit_id) REFERENCES units (id),
    amount NUMERIC NOT NULL,
    is_primary_measure BOOLEAN NOT NULL DEFAULT FALSE,
    is_converted BOOLEAN,
    raw_amount NUMERIC,
    CHECK (
        (
            is_primary_measure = TRUE
            AND is_converted IS NULL
        )
        OR (is_primary_measure = FALSE)
    ),
    CHECK (
        (
            is_converted = TRUE
            AND raw_amount IS NOT NULL
        )
        OR (
            is_converted IS NULL
            OR is_converted = FALSE
        )
    )
);
