# coding: utf-8

"""
    products

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from products_api.models.new_product_to_measure_post import NewProductToMeasurePost  # noqa: E501

class TestNewProductToMeasurePost(unittest.TestCase):
    """NewProductToMeasurePost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewProductToMeasurePost:
        """Test NewProductToMeasurePost
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewProductToMeasurePost`
        """
        model = NewProductToMeasurePost()  # noqa: E501
        if include_optional:
            return NewProductToMeasurePost(
                amount = 1.337,
                is_converted = True,
                is_primary_measure = True,
                raw_amount = 1.337,
                unit = 'fl oz'
            )
        else:
            return NewProductToMeasurePost(
                amount = 1.337,
                is_primary_measure = True,
                raw_amount = 1.337,
                unit = 'fl oz',
        )
        """

    def testNewProductToMeasurePost(self):
        """Test NewProductToMeasurePost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
