# coding: utf-8

"""
    products

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from products_api.models.new_product_post import NewProductPost  # noqa: E501

class TestNewProductPost(unittest.TestCase):
    """NewProductPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewProductPost:
        """Test NewProductPost
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewProductPost`
        """
        model = NewProductPost()  # noqa: E501
        if include_optional:
            return NewProductPost(
                gtin = '01234567',
                productname = '',
                sku = '',
                measures = None
            )
        else:
            return NewProductPost(
                gtin = '01234567',
                productname = '',
                measures = None,
        )
        """

    def testNewProductPost(self):
        """Test NewProductPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
