# coding: utf-8

"""
    products

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from products_api.api.handlers_marketplaces_api import HandlersMarketplacesApi  # noqa: E501


class TestHandlersMarketplacesApi(unittest.TestCase):
    """HandlersMarketplacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HandlersMarketplacesApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_get_marketplace(self) -> None:
        """Test case for get_marketplace

        """
        pass

    def test_get_marketplaces(self) -> None:
        """Test case for get_marketplaces

        """
        pass

    def test_post_marketplace(self) -> None:
        """Test case for post_marketplace

        """
        pass


if __name__ == '__main__':
    unittest.main()
