# coding: utf-8

"""
    products

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from products_api.models.new_marketplace import NewMarketplace  # noqa: E501

class TestNewMarketplace(unittest.TestCase):
    """NewMarketplace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewMarketplace:
        """Test NewMarketplace
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewMarketplace`
        """
        model = NewMarketplace()  # noqa: E501
        if include_optional:
            return NewMarketplace(
                name = ''
            )
        else:
            return NewMarketplace(
                name = '',
        )
        """

    def testNewMarketplace(self):
        """Test NewMarketplace"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
