# coding: utf-8

"""
    products

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from products_api.models.unit_symbol import UnitSymbol  # noqa: E501

class TestUnitSymbol(unittest.TestCase):
    """UnitSymbol unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitSymbol(self):
        """Test UnitSymbol"""
        # inst = UnitSymbol()

if __name__ == '__main__':
    unittest.main()
