-- Rename the misnamed marketplaces table to companies
ALTER TABLE marketplaces RENAME TO companies;

-- Drop the now obsolete physical_marketplaces table
DROP TABLE IF EXISTS physical_marketplaces;

-- Create the generic marketplaces table
CREATE TABLE marketplaces (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL REFERENCES companies(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ
);

-- Create the specialized physical_marketplaces table
CREATE TABLE physical_marketplaces (
    id INT PRIMARY KEY REFERENCES marketplaces(id) ON DELETE CASCADE,
    adr_address TEXT NOT NULL,
    place_id TEXT,
    open_location_code TEXT NOT NULL
);

-- Create the specialized online_marketplaces table
CREATE TABLE online_marketplaces (
    id INT PRIMARY KEY REFERENCES marketplaces(id) ON DELETE CASCADE,
    uri TEXT NOT NULL
);