# coding: utf-8

"""
    auth

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.handlers_auth_api import HandlersAuthApi  # noqa: E501


class TestHandlersAuthApi(unittest.TestCase):
    """HandlersAuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HandlersAuthApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_login_route(self) -> None:
        """Test case for login_route

        """
        pass

    def test_register_route(self) -> None:
        """Test case for register_route

        """
        pass


if __name__ == '__main__':
    unittest.main()
