DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'products_to_measures' AND column_name = 'id') THEN
        -- Drop the current primary key constraint
        ALTER TABLE products_to_measures DROP CONSTRAINT IF EXISTS products_to_measures_pkey;

        -- Drop the existing identity property
        ALTER TABLE products_to_measures ALTER COLUMN id DROP IDENTITY IF EXISTS;

        -- Create a new temporary column with the original type and identity
        ALTER TABLE products_to_measures ADD COLUMN old_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

        -- Copy data from the current column to the old column
        UPDATE products_to_measures SET old_id = id;

        -- Drop the current column
        ALTER TABLE products_to_measures DROP COLUMN id;

        -- Rename the old column to the original name
        ALTER TABLE products_to_measures RENAME COLUMN old_id TO id;

        -- Add the primary key constraint to the original column type
        ALTER TABLE products_to_measures ADD CONSTRAINT products_to_measures_pkey PRIMARY KEY (id);
    ELSE
        RAISE NOTICE 'Column "id" does not exist on table "products_to_measures", skipping DOWN migration.';
    END IF;
END $$;