DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'products_to_measures' AND column_name = 'id') THEN
        -- Drop the existing primary key constraint
        ALTER TABLE products_to_measures DROP CONSTRAINT IF EXISTS products_to_measures_pkey;

        -- Drop the existing identity property (if it exists)
        ALTER TABLE products_to_measures ALTER COLUMN id DROP IDENTITY IF EXISTS;

        -- Create a new temporary column with the desired type and identity
        ALTER TABLE products_to_measures ADD COLUMN new_id INTEGER GENERATED BY DEFAULT AS IDENTITY;

        -- Copy data from the old column to the new column
        UPDATE products_to_measures SET new_id = id;

        -- Drop the old column
        ALTER TABLE products_to_measures DROP COLUMN id;

        -- Rename the new column to the original name
        ALTER TABLE products_to_measures RENAME COLUMN new_id TO id;

        -- Add the primary key constraint to the new column
        ALTER TABLE products_to_measures ADD CONSTRAINT products_to_measures_pkey PRIMARY KEY (id);
    ELSE
        RAISE NOTICE 'Column "id" does not exist on table "products_to_measures", skipping UP migration.';
    END IF;
END $$;