name: lint

on:
    push:
        branches: [master]
        paths:
            - ".github/workflows/lint.rust.yml"
            - "**/*.rs"
            - "**/rustfmt.toml"
            - "**/clippy.toml"
            - "**/build.rs"
            - "**/Cargo.lock"
            - "**/Cargo.toml"
    pull_request:
        branches: [master]
        paths:
            - ".github/workflows/lint.rust.yml"
            - "**/*.rs"
            - "**/rustfmt.toml"
            - "**/clippy.toml"
            - "**/build.rs"
            - "**/Cargo.lock"
            - "**/Cargo.toml"

jobs:
    rustfmt:
        runs-on: ubuntu-latest
        if: github.event.pull_request.draft == false
        strategy:
            matrix:
                project:
                    - backend/auth
                    - backend/products
                rust: [stable]
                os: [ubuntu-latest]
        defaults:
            run:
                working-directory: ${{ matrix.project }}

        steps:
            - uses: actions/checkout@v3

            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                components: rustfmt

            - name: Rustfmt Check
              uses: actions-rust-lang/rustfmt@v1
