name: test

on:
    push:
        branches: [master]
        paths:
            - ".github/workflows/test.rust.yml"
            - "**/*.rs"
            - "**/build.rs"
            - "**/Cargo.lock"
            - "**/Cargo.toml"
    pull_request:
        branches: [master]
        paths:
            - ".github/workflows/test.rust.yml"
            - "**/*.rs"
            - "**/build.rs"
            - "**/Cargo.lock"
            - "**/Cargo.toml"

jobs:
    test:
        name: cargo test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                project:
                    - backend/auth
                    - backend/products
                    - packages/common-rs
                    - packages/validator-rs
                rust: [stable]
                os: [ubuntu-latest]
        defaults:
            run:
                working-directory: ${{ matrix.project }}

        steps:
            - uses: actions/checkout@v3
            - uses: actions-rust-lang/setup-rust-toolchain@v1

            - name: Run Tests
              run: cargo test --all

            # - name: Upload test coverage (optional)
            #   if: matrix.project == 'your_main_project' && matrix.rust == 'stable'
            #   uses: codecov/codecov-action@v3
            #   with:
            #     token: ${{ secrets.CODECOV_TOKEN }} # Replace with your Codecov token
            #     files: ${{ matrix.project }}/coverage/*.lcov # Adjust path if necessary
            #     fail_ci_if_error: true
            #     flags: ${{ matrix.project }} # Optional project flag
            #     name: ${{ matrix.project }}-coverage # Optional name
